FLOW_PORTAL_SITE = 'https://learn.concord.org'
FLOW_PORTAL_SSO_CLIENT_ID = 'dataflow'
FLOW_PORTAL_SSO_CLIENT_SECRET = '** ENTER SECRET HERE ***'

FIREBASE_ENABLED = True
FIREBASE_ENVIRONMENT = 'production'

FIREBASE_API_KEY = '** ENTER KEY HERE **'
FIREBASE_MESSAGE_SENDER_ID = '** ENTER MESSAGE SENDER ID HERE **'
FIREBASE_PROJECT_ID = '** ENTER PROJECT ID HERE **'
FIREBASE_CLIENT_EMAIL = '** ENTER CLIENT EMAIL HERE **'
FIREBASE_PRIVATE_KEY = '** ENTER PRIVATE KEY HERE (ensure trailing \n is kept) **'

FIREBASE_SEND_SENSOR_DATA_ENABLED = True
FIREBASE_SEND_SENSOR_DATA_INTERVAL = 1
